// Generated by natu

extern const char natu_bgHill_ImgData[];
extern const char natu_bgHill_MapData[];
extern const char natu_bgHill_PalData[];
extern const char natu_bgMenufull_ImgData[];
extern const char natu_bgMenufull_MapData[];
extern const char natu_bgMenufull_PalData[];
extern const char natu_bgTitle_ImgData[];
extern const char natu_bgTitle_MapData[];
extern const char natu_bgTitle_PalData[];

const char * const natuBgImgData[] = {
  &natu_bgHill_ImgData,
  &natu_bgMenufull_ImgData,
  &natu_bgTitle_ImgData,
};
const char * const natuBgMapData[] = {
  &natu_bgHill_MapData,
  &natu_bgMenufull_MapData,
  &natu_bgTitle_MapData,
};
const char * const natuBgPalData[] = {
  &natu_bgHill_PalData,
  &natu_bgMenufull_PalData,
  &natu_bgTitle_PalData,
};
