# Generated by natu


type
  Background* = enum
    bgHill
    bgMenufull
    bgTitle

block:
  {.compile:"./backgrounds/bgHill.c".}
  {.compile:"./backgrounds/bgMenufull.c".}
  {.compile:"./backgrounds/bgTitle.c".}
  {.compile:"./backgrounds.c".}

let natuBgImgData {.importc, codegenDecl:"extern const $# $#".}: array[Background, cstring]
let natuBgMapData {.importc, codegenDecl:"extern const $# $#".}: array[Background, cstring]
let natuBgPalData {.importc, codegenDecl:"extern const $# $#".}: array[Background, cstring]

const staticBgData: array[Background, BgData] = [
  bgHill: BgData(kind: bkReg4bpp, w: 32, h: 32, imgWords: 360, mapWords: 512, palHalfwords: 16, palOffset: 0, tileOffset: 0, flags: {bfScreenblock}, regions: @[], tileComp: None, mapComp: None),
  bgMenufull: BgData(kind: bkReg4bpp, w: 32, h: 32, imgWords: 240, mapWords: 512, palHalfwords: 16, palOffset: 1, tileOffset: 5, flags: {}, regions: @[], tileComp: None, mapComp: None),
  bgTitle: BgData(kind: bkReg4bpp, w: 32, h: 32, imgWords: 264, mapWords: 512, palHalfwords: 16, palOffset: 2, tileOffset: 3, flags: {}, regions: @[], tileComp: None, mapComp: None),
]

template data*(bg: Background): BgData = staticBgData[bg]
template palDataPtr*(bg: Background): pointer = natuBgPalData[bg]
template mapDataPtr*(bg: Background): pointer = natuBgMapData[bg]
template imgDataPtr*(bg: Background): pointer = natuBgImgData[bg]

