# Generated by natu

import natu/[memory, oam, utils]


type
  Graphic* = enum
    gfxPet
    gfxBerry
    gfxCursor
    gfxCloud
    gfxBalloon
    gfxBall
    gfxSoap
    gfxSelect

block:
  {.compile:"./graphics.c".}

let palData {.importc:"natuGfxPalData", extern:"natuGfxPalData", codegenDecl:"extern const $# $#".}: array[61, char]
let imgData {.importc:"natuGfxImgData", extern:"natuGfxImgData", codegenDecl:"extern const $# $#".}: array[14849, char]

const staticGfxData: array[Graphic, GraphicData] = [
  gfxPet: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 0, imgWords: 1920, palNum: 0, palPos: 0, palHalfwords: 16, frames: 15, frameWords: 128),
  gfxBerry: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 7680, imgWords: 128, palNum: 0, palPos: 0, palHalfwords: 16, frames: 1, frameWords: 128),
  gfxCursor: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 8192, imgWords: 128, palNum: 1, palPos: 32, palHalfwords: 14, frames: 1, frameWords: 128),
  gfxCloud: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 8704, imgWords: 128, palNum: 1, palPos: 32, palHalfwords: 14, frames: 1, frameWords: 128),
  gfxBalloon: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 9216, imgWords: 640, palNum: 1, palPos: 32, palHalfwords: 14, frames: 5, frameWords: 128),
  gfxBall: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 11776, imgWords: 128, palNum: 1, palPos: 32, palHalfwords: 14, frames: 1, frameWords: 128),
  gfxSoap: GraphicData(bpp: 4, size: s32x32, flags: {}, w: 32, h: 32, imgPos: 12288, imgWords: 128, palNum: 1, palPos: 32, palHalfwords: 14, frames: 1, frameWords: 128),
  gfxSelect: GraphicData(bpp: 4, size: s64x64, flags: {}, w: 64, h: 64, imgPos: 12800, imgWords: 512, palNum: 1, palPos: 32, palHalfwords: 14, frames: 1, frameWords: 512),
]

var palUsages {.codegenDecl:EWRAM_DATA.}: array[2, uint16]

template data*(g: Graphic): GraphicData = staticGfxData[g]
template palUsage*(g: Graphic): var uint16 = palUsages[g.data.palNum]
template palDataPtr*(g: Graphic): pointer = unsafeAddr palData[g.data.palPos]
template imgDataPtr*(g: Graphic): pointer = unsafeAddr imgData[g.data.imgPos]

