# Generated by natu

let soundbankBin* = static staticRead("./soundbank.bin").MmSoundbankPtr
  ## Pointer to your game's soundbank data.

type
  Sample* {.size: 4.} = enum
    sfxChirp
    sfxGiggle
    sfxPop
  Module* {.size: 4.} = enum
    modOct
